import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom'; // Updated import for React Router v6
import FixedBackground from '../Images/cimg4.webp';
const EventPage = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [activeEvent, setActiveEvent] = useState("All Events");

  const navigate = useNavigate(); // React Router's navigate for navigation

  const openNav = () => {
    setIsOpen(true);
  };

  const closeNav = () => {
    setIsOpen(false);
  };

  const events = {
    "Alfresco": [
      {
        title: "Capture and Conquer",
        registrationFees: "200 per team",
        status: "Inactive",
        image: "",
        tagline: '',
        description: "Embrace the thrill of ‘Capture and Conquer’ at our college fest!! “Capture and Conquer” is an interactive scavenger hunt game designed to engage participants in a fun, creative challenge where they must bring, click pictures, or make videos of specific items, places, or activities. The game revolves around a list of challenges, each requiring participants to find and document particular objects, locations, or actions.Unleash your competitive spirit, forge bonds and relish the unforgettable adventure that awaits.Dare to conquer the game.",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: {
          perTeam: 200 ,
          perPerson: '',
          singleBoy: '',
          singleGirl: '',
          Couple: '',
          Solo: '',
          Duet: '',
          perhead: ''
        },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '9 pm',
        rulebook: ""
      },
      {
        title: "Pictionary",
        registrationFees: "40 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Words or pictures, which one’s got more appeal? Explore Pictionary, and let’s see what you feel.",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "", perPerson: "40", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "" },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Squid Game",
        registrationFees: "70 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Step into the gripping world of ‘SQUID GAME’ at our thrilling event! Brace yourself for heart-pounding challenges, as you compete in four life-or-death games that demand skill, strategy, and nerves of steel. Win big or face the consequences. Dare to join us in this pulse-pounding, high-stakes adventure!",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "", perPerson: "70", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Paper Dance",
        registrationFees: "40 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: " With every step the story unfolds, Paper dance, where magic beholds!",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "40", perPerson: "", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Silent Giggles",
        registrationFees: "80 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Ready for a game that’ll leave you in stitches? In Silent Giggles, participants have to guess the word—but there’s a twist! With headphones on, they won’t hear a thing while their friends try to mime or describe the word. Get ready for misunderstandings and side-splitting laughter as you try to guess without a sound!",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "80", perPerson: "", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Treasure Hunt",
        registrationFees: "200 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "A treasure hunt as an informal event brings an element of playfulness and excitement to any gathering. Whether it’s a reunion, a backyard party, or a casual get-together with friends, a treasure hunt adds an extra layer of fun and camaraderie. Participants form teams, each armed with a list of clues and riddles that lead them on a thrilling chase to find the hidden treasure. Laughter and cheers echo through the surroundings as the teams race against the clock, solving puzzles and following hints that lead them to various locations. The hunt encourages teamwork, problem-solving, and a dash of friendly competition, fostering bonds between participants as they embark on a shared adventure. In the end, it’s not just about the treasure found but the joyful memories created along the way, making the treasure hunt an unforgettable highlight of the event.",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "200", perPerson: "", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Darty Secrets",
        registrationFees: "30 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "It is a casual version of the popular sport that is typically played in a relaxed and social setting, such as a pub or at home with friends. It involves throwing small, pointed darts at a circular dartboard fixed to a wall. The main objective is to score points by hitting specific areas on the board",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "", perPerson: "30", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Songstravaganza",
        registrationFees: "120 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Welcome to the ultimate song showdown! Get ready for a whirlwind of melodies, lyrics, and laughter as we dive into a series of fun-filled music games. Whether you’re a pop culture pro or just love to sing along, this is your time to shine. Let the music madness begin!",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "120", perPerson: "", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "SwiftMingle",
        registrationFees: "Boys - 120, Girls - 100",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Speed Dating. Rotate-a-date… Move in or move on",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "1",
        fees: { perTeam: "", perPerson: "", singleBoy: "120", singleGirl: "100", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Tambola",
        registrationFees: "40 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "So many of our childhood memories are incomplete without the game of tambola. Make more precious memories with your friends and elevate your competitive spirit by participating in this fun game.",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "", perPerson: "40", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Evening Amore",
        registrationFees: "Couple entry - 150, Single girls - 100, Single boys - 120",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Participants will embark on a rollercoaster journey of blind dating, experiencing the thrill of meeting someone new, complete with a series of engaging and entertaining games designed to bring out the highs and lows of romance. Whether it’s the spark of connection or the unpredictability of first impressions, this event promises an evening full of excitement, surprises, and memorable moments.",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "2",
        fees: { perTeam: "", perPerson: "", singleBoy: "120", singleGirl: "100", Couple: "150", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Musical Chairs",
        registrationFees: "30 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Friends gather in a circle of chairs, with one less chair than the number of participants. ",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "", perPerson: "30", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Soul Sync",
        registrationFees: "80 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Are you and your partner truly in sync? Best friends, couples, or even soul mates—this is your chance to prove! Answer questions about each other and see how well you really know your other half. Get it right, and victory is yours. Beware; one wrong answer could break the sync😵. Are you ready to play and see if your bond is unbreakable?",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "80", perPerson: "", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Drape It",
        registrationFees: "50 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Participants showcase their draping skills, blending tradition and modernity.",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "50", perPerson: "", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Your Pace or Mine?",
        registrationFees: "30 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Dumb Charades",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "", perPerson: "30", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Balloon Burst",
        registrationFees: "40 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Join the ultimate Balloon Burst Frenzy, where the fun never stops and every pop counts!! It’s a race against the clock and your friends- who will rise to the top as the ultimate balloon buster? Ready, set, burst!!!",
        teamSize: "",
        minteamSize: "1",
        maxteamSize: "15",
        fees: { perTeam: "40", perPerson: "", singleBoy: "", singleGirl: "", Couple: "", Solo: "", Duet: "", perhead: "", },
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      // More events...
    ],
"Chorea": [
      {
        title: "Nritya Sangam",
        registrationFees: "Solo: 150/- | Duet: 250/- | Group: 80/-(per head)",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'The Confluence of Classical Elegance',
        description: "A Classical/Folk dance competition is a celebration of tradition creativity and the enduring legacy of classical and folk dances creating a captivating experience that honours the depth and diversity of our cultural roots.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"150",Duet:"250",perhead:"80"},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1Q9vZsmt70Fi9HolqA0xVdrNbzSCFyYL_/view?usp=drive_link"
      },
      {
        title: "Ballismus",
        registrationFees: "Solo: 150/- | Duet: 250/- | Group: 80/-(per head)",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Dust off your boots and Dance.',
        description: "  Get ready to mesmerize the audience with your dancing skills! Ballismus is an inter-university dance competition that brings together talented dancers from across the country. Whether you’re a seasoned performer or an enthusiastic beginner, this platform is yours to shine. Choose your style- Western, Bollywood, or Fusion - and take the stage by storm!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"150",Duet:"250",perhead:"80"},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1F7xah0Eg0EjdWMpfjt4lG82WbHedlZ0o/view?usp=drive_link"
      },
      {
        title: "Street Blaze",
        registrationFees: "Solo: 100/- | Duet: 150/- | Group: 50/-(per head)",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Turn up the heat, set the street on blaze',
        description: "Get ready to witness the energy passion and raw talent as dancers come together for an electrifying battle of rhythm and style. This is more than just a competition—it's a celebration of culture creativity and the unbreakable spirit of street dance. So, lace up your kicks, turn up the music, and get ready to feel the beat. The streets are calling—let the battles begin!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"100",Duet:"150",perhead:"50"},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1loHlXShy4UrsYyS_PvuVoY8qcidAA1Oc/view?usp=drive_link"
      },
      {
        title: "Adaptune",
        registrationFees: "Solo: 80/- | Duet: 150/-",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Step into the spotlight-Adaptune awaits your flair for dance',
        description: "Join us for a dynamic and exhilarating dance experience at 'ADAPTUNE'. In this one-of-a-kind event you'll dance to spontaneously selected viral songs revealed just one minute before you hit the floor. Whether you're a seasoned dancer or a novice looking for fun, this event promises a high-energy, interactive experience where every moment counts. Gather your friends, bring your best moves, and let the rhythm guide you through an unforgettable night of dance and excitement!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"2",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"80",Duet:"150",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/17nVDakfL9nVjZ-XTLBhGditnBKlTeEsZ/view"
      },
      {
        title: "Blossoming Steps – Couple Dance",
        registrationFees: "200 per couple",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Growing Together, One Dance at a Time',
        description: "Blossoming Steps' is a couple dance event that takes participants through a journey of relationship growth using Knapp's Model as inspiration.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"2",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"200",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1gIpufCBxabeJpQaqbvAn3YXh_B-LRFAo/view?usp=drive_link"
      },

    ],
    "Kalakriti": [

      {
        title: "Fantasy Faces",
        registrationFees: "₹100 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Transforming faces, from blank canvases to living art!',
        description: "Prepare to witness a kaleidoscope of colours, dazzling designs, and artistic mastery as participants transform faces into mesmerizing works of art.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"100",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '10-Oct-2024',
        venue: 'Mini Audi',
        time: '10:30AM- 12:30 PM',
        rulebook: ""
      },

      {
        title: "Caffeine Creations",
        registrationFees: "₹30 per individual",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'From Beans to Brushes,awaken your creativity with the mesmerizing aroma of art!',
        description: " Join our Coffee Painting Competition and let the rich hues of coffee brew beauty on your canvas.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"30",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '10-Oct-2024',
        venue: 'Mini Audi',
        time: '1:30-3:00 PM',
        rulebook: ""
      },
      {
        title: "Brushless Strokes",
        registrationFees: "₹50 per individual",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Explore the world beyond brushes & embrace the art of free expression!',
        description: "Unleash your hidden creativity and think outside the box to create a masterpiece with anything other than a brush.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"50",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '11-Oct-2024',
        venue: 'Mini Audi',
        time: '1:30-3:30 PM',
        rulebook: ""
      },
      {
        title: "Acrylic Odyssey",
        registrationFees: "₹80 per individual",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Bold pigments blend, a symphony of art,With acrylic strokes, masterpieces start.',
        description: "With a boundless palette of colors and a canvas to make your own, let your brushstrokes tell a story, and vie for the title of The Master of Acrylics",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"80",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '10:00AM- 12:30 PM',
        venue: 'Mini Audi',
        time: '12-Oct-2024',
        rulebook: ""
      },

      {
        title: "Tattoo Tales",
        registrationFees: "₹50 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Transient Tattoos, Lasting Impressions!',
        description: "Unleash the full extent of your artistic prowess as you blend the vibrancy of acrylic paint with deft brushstrokes to craft stunning temporary tattoos.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"50",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '12-Oct-2024',
        venue: 'Mini Audi',
        time: '1:30-3:30 PM',
        rulebook: ""
      },
      {
        title: "Contrast Chronicles",
        registrationFees: "₹20 per individual",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Sketching whispers, dreams take shape With strokes of graphite, worlds escape.',
        description: "Welcome to a B&W sketching competition, where we eagerly anticipate your monochrome masterpiece to dazzle us.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"20",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '13-Oct-2024',
        venue: 'Mini audi',
        time: '1:30-3:00 PM',
        rulebook: ""
      },

      {
        title: "Splash Tees",
        registrationFees: "₹150 per individual",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Brushstrokes on fabric, colors ignite,T shirt transformed, a wearable delight!',
        description: "Get ready to unleash your inner artist and splash your creativity onto a humble canvas of a T shirt in our exhilarating T shirt painting competition.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"150",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '  14-Oct-2024 ',
        venue: 'Mini Audi',
        time: '10:00AM- 12:00 PM',
        rulebook: ""
      },
      {
        title: "Mehendi Mania",
        registrationFees: "₹30 per individual",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'An imprint of tradition, nature’s blossoms on your palms!',
        description: "Let the rich earthy scent of mehndi, guide your creativity and lead you to the finish line, in this mehndi designing competition.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"30",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: ' 14-Oct-2024 ',
        venue: 'Mini Audi',
        time: '1:30PM- 3:00 PM',
        rulebook: ""
      },
      {
        title: "Brush Of Pebbles",
        registrationFees: "₹50 per individual",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: "On rugged stones, colors bloom and play Nature's canvas adorned, a rock's display!",
        description: "Welcome to this stone painting competition, where rocks transform into galleries. An amazing blend of human imagination with the beauty of nature.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"50",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '14-Oct-2024',
        venue: 'Mini Audi',
        time: '3:15PM- 5:15PM',
        rulebook: ""
      },

    ],
 "Littmania": [
      {
        title: "Cineholics",
        registrationFees: "Rs.60 for team of 3 || Rs. 50 for team of 2  || Rs.30 for lonewolves",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: " Your ultimate movie and mega fandom quiz experience! Dive into the captivating world of cinema, web series, and OTT platforms as we test your knowledge and passion for the screen. Whether you're a film buff or a series enthusiast, this is your chance to shine and enjoy a thrilling challenge. Gather your friends, get ready to engage, and most importantly, have a fantastic time. Let the quiz begin and may the best cinephiles win!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"3",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:"",lonewolves:"30",twolonewolves:"50",threelonewolves:"60"},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '10 October, 2024',
        venue: 'LT3',
        time: '9:00am',
        rulebook: "https://drive.google.com/file/d/1BxX2XTXjOZErnUdu_hUpmvpoaZgIxJ_3/view?usp=drive_link"
      },
      {
        title: "Cognizzia",
        registrationFees: "Rs.180/- per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "COGNIZZIA is an engaging and informative General Quiz that challenges participants with a diverse range of questions across various topics. Whether you are a trivia enthusiast or simply seeking to expand your knowledge, COGNIZZIA offers an enjoyable experience that stimulates the mind. Test your expertise on history, science, pop culture, geography, and much more, as you navigate through thought-provoking questions and discover fascinating facts. Sharpen your cognitive skills and have fun while exploring a world of intriguing information with COGNIZZIA: General Quiz.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"180",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '11th October , 2024 ',
        venue: '',
        time: '9:00 A.M',
        rulebook: "https://drive.google.com/file/d/1vRT1WzhpwcX0iH5DPnKfYni5lcMr_QK-/view?usp=drive_link"
      },
      {
        title: "Biocrux Jr.(MedQuiz)",
        registrationFees: "Rs. 180/- per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Subjects: All pre and para clinical subjects",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"180",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '12/10/2024',
        venue: '',
        time: '09.00 AM onwards',
        rulebook: "https://drive.google.com/file/d/1L9qMfCZdMDlXgDPMq3P1zP8zKvfXKzkI/view?usp=drive_link"
      },
      {
        title: "Biocrux Sr.(MedQuiz)",
        registrationFees: "Rs. 210/- per team (Only 1 intern per team is allowed)",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Subjects: All relevant clinical knowledge!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"210",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '13/10/2024',
        venue: 'Main Auditorium',
        time: ' 09.00 AM onwards',
        rulebook: "https://drive.google.com/file/d/1Tp050gHuWs8pANsC8mJAKdzVFRMFODxj/view?usp=drive_link"
      },
      {
        title: "Anime Quiz",
        registrationFees: "Rs. 180/- for a team of 4",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Get ready to test your knowledge of the vibrant world of anime .Join our anime quiz and showcase your expertise on various genres,characters and storylines . From classic mainstream series (Naruto, one-piece ,Bleach,death note , one punch man ,etc)to the latest releases(demon slayer , Jjk , chainsaw man , etc), our questions and rounds will challenge even the most dedicated otakus.Our quiz revolve around genre like action , romance, shounen , seinen , drama , etc and includes little to no manga , manhwa or manhua questions .",
        teamSize: "",
        minteamSize:"4",
        maxteamSize:"4",
        fees:{perTeam:"180",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '14 October 2024',
        venue: 'LT3',
        time: '9:00am',
        rulebook: "https://drive.google.com/file/d/1cAHUib62XU5gRm873b3I5qa_BN5CdAQ5/view?usp=drive_link"
      },
      {
        title: "Iconic Impressions ",
        registrationFees: "Rs. 50 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Join us in this epic showcase of talents wherein participants enact the characters (from movies, books, sitcoms etc.) that they have grown up watching and have loved them dearly. Let the wheel of fortune do its wonders and be the chosen one reenacting your character. And the best part, let your creativity flow by imagining them in a totally different scenario.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"50",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1NufiXpkxR7j9dQY-J61uEcUgG2o05fbi/view?usp=drive_link"
      },
      {
        title: "Unstory",
        registrationFees: "Rs. 120/- per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "An event bringing out the perfect blend of your writing prowess and quick thinking skills to string words together and turn them into a beautiful story but not in the conventional way storytellers do. Pyrexia brings you 'unstory' where let your story be a joint effort with your teammates and the topic be oblivious to you till the clock starts ticking.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"120",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1NBITEXWYSS-57Y15483vNZe8LAc-ImM_/view?usp=drive_link"
      }, {
        title: "Found poetry",
        registrationFees: "Rs. 50 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "This event is about seeing the world through a fresh lens, where words already exist but their new arrangement tells a different story. Dive into the world of found poetry, where creativity knows no bounds and inspiration is everywhere.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"50",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Literary Speed Dating",
        registrationFees: "Rs.60/- per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: " An event of literary connections where book lovers, aspiring writers, and literary enthusiasts come together to share their passions in a fast-paced, engaging format. In this unique event, you'll have the opportunity to meet a diverse range of fellow bibliophiles and discuss your favorite books, authors, and literary genres in brief, dynamic conversations that would ultimately decide your fate in the game.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"60",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Kavi Sammelan:",
        registrationFees: "Rs. 60/- per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "एक ऐसा मंच जहाँ शब्दों की अद्भुत कलाकारी और भावनाओं की गहराई का अनुभव होता है। यह साहित्यिक मिलन का अवसर है, जहाँ हर कविता एक नई सोच और दृष्टिकोण को प्रस्तुत करती है।",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"60",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1qyi7BKSrtp0yUk85CWcKrWKuKxp3pf3a/view?usp=drive_link"
      },
      {
        title: "Rhapsody",
        registrationFees: "Rs. 50/- per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Welcome to Rhapsody, where a series of evocative images guide your words to create a story that resonates them. Each picture holds a piece of a story—waiting for you to bring it to life.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"50",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Biocrux Jr",
        registrationFees: "Rs. 180/- per team || Rs. 60/- per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Subjects: All pre and para clinical subjects.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"180",perPerson:"60",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "The War of Wits(Debate Competition)",
        registrationFees: "Rs. 60/- per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: " Step into the cerebral arena of intellectual duels, where minds clash and ideas ascend to their zenith. Prepare to embark on a voyage of rhetoric and wit, where the art of persuasion takes center stage. Engage in the prestigious Parliamentary Debate Competition and let your arguments resonate with eloquence and conviction.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"60",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1flSNXaDMXyqxkM-DnQrIC-XLde8o84hY/view?usp=drive_link"
      },
      {
        title: "JAM",
        registrationFees: "Rs. 60/- per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: " Ladies and gentlemen, welcome to our exciting Just a Minute competition (JAM Session) Hereby, have two thrilling rounds of wordplay and wit where our competitors will showcase their skills in maintaining fluency, precision, and creativity under the pressure of the ticking clock.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"60",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1sf1IW6e801X-LdYbL7Zv4ibgpz9FNkXr/view?usp=drive_link"
      },



    ],
"Sinfonia": [
      {
        title: "TARANG: Indian Singing",
        registrationFees: "Solo: ₹150 | Duet: ₹200 | Group: ₹400",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Soulful symphonies from the subcontinent',
        description: "Tarang - The Indian singing competition offers a stellar platform to showcase your expertise in Indian light music semi-classical Bollywood or folk genres. Embrace the opportunity to captivate the audience with your melodious voice!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"150",Duet:"200",perhead:"",groupTeam:"400"},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1IsYoMANTOpeGmKkyHEH0ICmGyVg-CuL7/view?usp=drive_link"
      },
      {
        title: "Euphonia: Western Singing",
        registrationFees: "Solo: ₹150 | Duet: ₹200 | Group: ₹400",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Euphonia Glory—Where Every Note Tells a Story!',
        description: "Euphonia: Western Singing Competition - Witness the raw power of the human voice in this electrifying singing competition where harmony reigns supreme. Each note, each harmony is pure talent and skill. Feel the energy as participants compete, blending voices in intricate arrangements that push the boundaries of vocal music. Who will rise above and claim the title of Euphonic champion?",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"150",Duet:"200",perhead:"",groupTeam:"400"},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1xRuSZXRGbB-KLvV_xECnP04m9wsxzhBO/view?usp=drive_link"
      },
      {
        title: "METALLICA",
        registrationFees: "Single: Rs 200 | Duet: Rs 300",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Unleash Your Instrumental Fury and Set the Stage Ablaze',
        description: "Are you ready to let your instruments speak and your skills dazzle? Join us at Metallica where your chance to shine awaits! This high-energy competition invites instrumentalists from all backgrounds to showcase their prowess and electrify the stage with their talent. Whether you wield a guitar, drum, violin, or any other instrument, Metallica is your platform to demonstrate your virtuosity and creativity. Compete for thrilling prizes and the chance to become the ultimate instrumental champion. Don't miss this opportunity to make your mark and set the stage on fire with your exceptional skills. Step up, show off, and let your music roar!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"200",Duet:"300",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/10gkv29sR63ilc9Uec2282_siGZdNcN3f/view?usp=drive_link"
      },
      {
        title: "BATTLE OF BANDS",
        registrationFees: "Rs 1000 per band",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Ignite the Stage Rock the Fest',
        description: "Are you ready to turn up the volume and unleash your musical prowess? Join us at Pyrexia 4.0 for the ultimate Battle of the Bands! This electrifying competition is your chance to showcase your band's talent, energy, and creativity in front of an enthusiastic crowd. Compete for top honors and exciting prizes as you go head-to-head with the best musical acts in college. Whether you rock, groove, or experiment with unique sounds, this is your moment to shine. Sign up now and get ready to claim your spot as the reigning champions of Pyrexia!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"1000",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1KME7mWpIdjJ9mdQW_KNL6LRtJbOPfqIH/view?usp=drive_link"
      },
      {
        title: "RHYTHM REVOLUTION - RAP BATTLE AND BEATBOXING",
        registrationFees: "Solo: ₹100 | Duet: ₹150",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Voice the words. Dominate the beat.',
        description: "Unleash your lyrical and rhythmic genius at our Rap and Beatboxing Battle! This competition is the right opportunity for you to battle it out with fellow contestants in a high-energy face-off, where creativity, flow, and originality reign supreme. Show us what you've got and claim the title of the Revolutionist!",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"100",Duet:"150",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1bYcp1_0lwpZKrcQNzbO3LH-LIUDC7uOK/view?usp=drive_link"
      },

    ],
    "Thespians": [
      {
        title: "Nukkad Natak",
        registrationFees: "Rs 500 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Drama Beyond the Walls',
        description: "A Nukkad Natak is a form of street theatre in India that uses a mix of dialogue, music, and dance to address social issues and entertain audiences. Performed in open spaces, it aims to engage the public with its vibrant and interactive storytelling.",
        teamSize: "3-5",
        minteamSize:"3",
        maxteamSize:"5",
        fees:{perTeam:"500",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/13vWvQHKbljpjy1VjoNtXTfD8c7zUNFtp/view?usp=drive_link" // This can be optional
      },
      {
        title: "Echoes of Expressions: Monoact and Mime competition",
        registrationFees: "Rs 120 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'One Stage, Infinite Expressions',
        description: "The Monoact Competition is an exciting theatrical event that showcases the talent and versatility of participants as they take the stage alone to perform captivating solo acts. Mime is a unique and captivating form of non-verbal performance art that relies solely on body movements, gestures, facial expressions, and actions to convey emotions, tell stories, and communicate with the audience.",
        teamSize: "3-5",
        minteamSize:"3",
        maxteamSize:"5",
        fees:{perTeam:"120",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1cK-tw-2qkzzNkYRjA2AhvM9cq8DzUQ5p/view?usp=drive_link" // This can be optional
      },

      // Add more events as needed
      {
        title: "COMIC-COMBAT: STAND-UP COMEDY",
        registrationFees: "Rs 100 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'Where Jokes Take the Stage and Laughter Reigns Supreme',
        description: "Comic Combat is a vibrant intercollege comedy competition that showcases the freshest comedic talent in PYREXIA 2024. Participants face off in a high-energy contest delivering their best stand-up routines to win over the audience and judges. Expect a night filled with memorable performances, spontaneous laughs, and fierce competition as the funniest college comedians battle it out for the top spot.",
        teamSize: "3-5",
        minteamSize:"3",
        maxteamSize:"5",
        fees:{perTeam:"",perPerson:"100",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "" // This can be optional
      },
      // Add more events as needed
      {
        title: "MADD ANGLE",
        registrationFees: "Rs 100 per person",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: 'DRAMA bhi DEAL bhi',
        description: "In Madd Angle, participants (solo or team) will be given a random prop impromptu and will have to bring it to life through either a captivating sales pitch or a dramatic performance. Whether it's through persuasive storytelling or engaging drama, each performance promises to be a one-of-a-kind experience.",
        teamSize: "3-5",
        minteamSize:"3",
        maxteamSize:"5",
        fees:{perTeam:"",perPerson:"100",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1blMAhADdQmcWgLqNrtIWbilb-lpN4V7S/view?usp=drive_link" // This can be optional
      },
    ],
    "Thunderbolt": [
      {
        title: "Mortal Kombat",
        registrationFees: "Rs 75/-",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Knockout matches with the winner from each pool advancing to the finals.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"75",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "Rs 1500/-",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1zHZR1yCkuo3CRVBGySaGyqF_1QrsAqIM/view?usp=drive_link"
      },
      {
        title: "COD MOBILE (MULTIPLAYER)",
        registrationFees: "₹300 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Multiplayer COD Mobile tournament with knockout matches, maps, and modes fixed after fixtures.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"300",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "Rs 4000/-",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1uMjBhDTzLcb0MG7YOYi4ZZ54KCjg9Kmv/view?usp=drive_link"
      },
      {
        title: "TEKKEN",
        registrationFees: "Rs 75/-",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Knockout matches with the winner from each pool advancing to the finals.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"75",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "Rs 450/-",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1iwrVdEmrzlnQLJuGyNalTCw2F76s8ryf/view?usp=drive_link"
      },
      {
        title: "FIFA",
        registrationFees: "Rs 180/-",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "Knockout FIFA matches with winners from each pool advancing to the finals.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"",perPerson:"180",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "Rs 2500/-",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1Nh-C3Div0TMFjYe-oF96BMwCWCnaraCf/view?usp=drive_link"
      },
      {
        title: "BGMI (BATTLE ROYALE)",
        registrationFees: "₹400 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "BGMI tournament with league stage and final round, top 16 teams advance to final.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"400",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "₹10000",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1r__Vl1AUoiKjflXMT41cyhbbo7I_dHeP/view?usp=drive_link"
      },
      {
        title: "BGMI (TEAM DEATH MATCH)",
        registrationFees: "₹200 per team",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "BGMI Team Death Match with 4 players per team, first team to 40 kills wins.",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"200",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "Trophy + Cash prize",
        date: '',
        venue: '',
        time: '',
        rulebook: "https://drive.google.com/file/d/1r__Vl1AUoiKjflXMT41cyhbbo7I_dHeP/view?usp=drive_link"
      },
    ],
    "Velocity": [

      {
        title: "Girls Basketball",
        registrationFees: "1000",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"20",
        fees:{perTeam:"1000",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "2100(First)/1500(Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Boys Basketball",
        registrationFees: "1400",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"20",
        fees:{perTeam:"1000",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "5100 (First)/2100(Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Table Tennis Singles",
        registrationFees: "150",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"150",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "1100 (First), 700 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Table Tennis Doubles",
        registrationFees: "300",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"20",
        fees:{perTeam:"300",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "2100 (First), 1100 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Table Tennis Mixed Doubles",
        registrationFees: "300",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"300",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "2100 (First), 1100 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Girls Kabaddi",
        registrationFees: "1000",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"1000",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "2100 (First)/1400(Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Boys Kabaddi",
        registrationFees: "1200",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"1200",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "2500(First)/1500(Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Volleyball",
        registrationFees: "1500",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"1500",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "21000",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Football (Boys Only)",
        registrationFees: "2500",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"2500",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "10000 (First), 4800 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Futsal (Boys Only)",
        registrationFees: "1400",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"1400",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "5800 (First), 2800 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Tennis Singles",
        registrationFees: "150",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"150",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "1100 (First), 700 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Tennis Doubles",
        registrationFees: "300",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"300",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "2100 (First), 1100 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Tennis Mixed Doubles",
        registrationFees: "300",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"300",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "2100 (First), 1100 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Chess",
        registrationFees: "100 for Rapid, Blitz and Bullet categories, 500 for team event",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"15",
        fees:{perTeam:"500",perPerson:"100",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Badminton Singles",
        registrationFees: "225",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"2",
        fees:{perTeam:"225",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "2500 (First), 1500 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Badminton Doubles",
        registrationFees: "450",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"4",
        fees:{perTeam:"450",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "4100 (First), 2100 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },
      {
        title: "Badminton Mixed Doubles",
        registrationFees: "450",
        status: "Inactive",
        image: "https://example.com/subevent1_1.jpg",
        tagline: '',
        description: "",
        teamSize: "",
        minteamSize:"1",
        maxteamSize:"8",
        fees:{perTeam:"450",perPerson:"",singleBoy:"",singleGirl:"",Couple:"",Solo:"",Duet:"",perhead:""},
        contact1Name: '',
        contact1: '',
        contact2Name: '',
        contact2: '',
        contact3Name: '',
        contact3: '',
        prize: "4100 (First), 2100 (Second)",
        date: '',
        venue: '',
        time: '',
        rulebook: ""
      },


    ]

  };
  const allSubEvents = Object.keys(events).flatMap(event => events[event]);

  const handleEventClick = (event) => {
    setActiveEvent(event);
  };

  // Function to navigate to sub-event details page
  const goToSubEventDetails = (subEvent) => {
    navigate('/subevent-details', { state: { subEvent } }); // Using navigate to handle page navigation
  };

  // Define different background styles
  const gradientColors = [
    "bg-gradient-to-br from-blue-400 via-blue-200 to-white",
    "bg-gradient-to-br from-red-400 via-red-200 to-white",
    "bg-gradient-to-br from-green-400 via-green-200 to-white",
    "bg-gradient-to-br from-yellow-400 via-yellow-200 to-white",
    "bg-gradient-to-br from-purple-400 via-purple-200 to-white",
    "bg-gradient-to-br from-teal-400 via-teal-200 to-white",
    "bg-gradient-to-br from-orange-400 via-orange-200 to-white",
    "bg-gradient-to-br from-pink-400 via-pink-200 to-white",
    "bg-gradient-to-br from-indigo-400 via-indigo-200 to-white",

    "bg-gradient-to-br from-gray-400 via-gray-200 to-white",
    "bg-gradient-to-br from-amber-400 via-amber-200 to-white",
    "bg-gradient-to-br from-violet-400 via-violet-200 to-white",
    "bg-gradient-to-br from-fuchsia-400 via-fuchsia-200 to-white",
    "bg-gradient-to-br from-rose-400 via-rose-200 to-white",
    "bg-gradient-to-br from-emerald-400 via-emerald-200 to-white",
    "bg-gradient-to-br from-sky-400 via-sky-200 to-white",
    "bg-gradient-to-br from-stone-400 via-stone-200 to-white",
    "bg-gradient-to-br from-neutral-400 via-neutral-200 to-white",
    "bg-gradient-to-br from-cyan-400 via-cyan-200 to-white",
    "bg-gradient-to-br from-lime-400 via-lime-200 to-white",
  ];



  // Function to get a gradient for each sub-event
  const getBackgroundStyle = (index) => {
    return gradientColors[index % gradientColors.length];
  };

  return (
    <div className="relative bg-cover bg-center bg-fixed font-sans-serif poppins min-h-screen mt-16" style={{
      backgroundImage: `url(${FixedBackground})`, backgroundSize: 'cover',
      backgroundPosition: 'center',
      height: '100%',
      width: '100%',
    }}>
      {/* Sidebar for event categories */}
      <div className={`fixed top-0 mt-16 left-0 h-full bg-[#001f3f] text-white transition-all ${isOpen ? 'w-64' : 'w-0'} overflow-x-hidden`}>
        <button className="absolute top-0 mt-4 right-4 bg-[#001f3f] text-3xl text-white" onClick={closeNav}>
          &times;
        </button>
        <div className="mt-16 flex flex-col space-y-4 px-8 ">
          <button onClick={() => handleEventClick("All Events")} className="text-lg hover:text-white text-left hover:font-bold">
            All
          </button>
          {Object.keys(events).map(event => (
            <button key={event} onClick={() => handleEventClick(event)} className="text-lg hover:text-grey text-left hover:font-bold">
              {event}
            </button>
          ))}
        </div>
      </div>

      {/* Main content area */}
      <div className={`transition-all bg-cover bg-center bg-fixed p-4 ${isOpen ? 'ml-64' : 'ml-0'}`} >
        <button className="bg-[#001f3f] text-white py-2 px-4 rounded fixed " onClick={openNav}>☰</button>
        <h2 className="mt-6 mb-16 text-4xl md:text-6xl flex justify-center text-white font-semibold">{activeEvent === "All Events" ? "All Events" : activeEvent}</h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:gap-16 md:gap-12 gap-8 mt-4" >
          {(activeEvent === "All Events" ? allSubEvents : events[activeEvent]).map((subEvent, index) => (
            <div
              key={index}
              className={`rounded-lg shadow-lg p-4 ${getBackgroundStyle(index)} hover:bg-gradient-to-b transition-all duration-500`}
            >
              <div className="p-6 text-lg md:text-xl" >
                <h3 className="text-xl md:text-2xl font-semibold  mb-8">{subEvent.title}</h3>
                <p>Fees: {subEvent.registrationFees}</p>
                <p>Status: {subEvent.status}</p>
                <button
                  onClick={() => goToSubEventDetails(subEvent)}
                  className="text-[#001f3f] font-bold text-2xl hover:underline mt-1"
                >
                  →
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default EventPage;